# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('train_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_pore', models.FloatField(default=0)),
                ('score_wrinkle', models.FloatField(default=0)),
                ('score_pigmen', models.FloatField(default=0)),
                ('score_erythema', models.FloatField(default=0)),
                ('score_emotion', models.FloatField(default=0)),
                ('comment', models.TextField(default=None)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MeasuredData')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='measureddata',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
