# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinstatus',
            old_name='score_pigmen',
            new_name='score_pigmentation',
        ),
    ]
