# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171207_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureddata',
            name='user_info',
        ),
        migrations.AddField(
            model_name='skinstatus',
            name='score_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measureddata',
            name='image',
            field=models.ImageField(upload_to='images/test/'),
        ),
        migrations.AlterField(
            model_name='measureddata',
            name='measured_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
