# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171211_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinstatus',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
