# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171212_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/test/')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('is_train', models.BooleanField(default=True)),
                ('score_pore', models.FloatField(default=0)),
                ('score_wrinkle', models.FloatField(default=0)),
                ('score_pigmentation', models.FloatField(default=0)),
                ('score_erythema', models.FloatField(default=0)),
                ('score_emotion', models.FloatField(default=0)),
                ('score_total', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
