# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_skindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skindata',
            name='score_emotion',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='score_erythema',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='score_pigmentation',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='score_pore',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='score_wrinkle',
            field=models.FloatField(default=-1),
        ),
    ]
