# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171212_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinstatus',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='skindata',
            name='is_train',
        ),
        migrations.AddField(
            model_name='skindata',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MeasuredData',
        ),
        migrations.DeleteModel(
            name='SkinStatus',
        ),
    ]
