# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171212_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skindata',
            options={'ordering': ['-measured_at']},
        ),
    ]
